name: husky
description: Husky make it easy to manage your Dart and Flutter project's git hooks.
version: 0.1.2
homepage: https://hyiso.github.io/husky/
repository: https://github.com/hyiso/husky

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  args: ^2.3.1
  cli_util: ^0.3.5
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.17.0
