name: husky
description: Husky make it easy to manage git hooks for your Dart and Flutter projects. 
version: 0.1.5
homepage: https://github.com/hyiso/husky
repository: https://github.com/hyiso/husky

environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  args: ^2.3.1
  path: ^1.8.0

dev_dependencies:
  commitlint_cli: ^0.3.0-dev.2
  lint_staged: ^0.2.0-dev.0
  lints: ^2.0.0
  test: ^1.17.0

lint_staged:
  'lib/**.dart': dart fix --apply && dart format --fix